### ISSUE TITLE
is this works for msi modern 14 b4mw (r5 4500u) ?

### ISSUE THREAD

**Issue by Nagendra9Kumar** [saeidex/msi-modern-15#4]
iam unable to boot into installer

**Comment by saeidex** [comment]
![image](https://github.com/saeidex/ryzentosh-msi-modern-15/assets/112776380/aad8003c-b539-48e2-946c-cf7171b61a8e)
https://www.techpowerup.com/cpu-specs/ryzen-5-4500u.c2285

- 4500U based on `Renoir` arch.
- 5500U based on `Lucienne` arch.

But according to the NootedRed it supposed to to be work
![image](https://github.com/saeidex/ryzentosh-msi-modern-15/assets/112776380/f04fca72-c8a2-4cd4-a6b8-838182fe77c3)

Try to manually update the latest version of nootedred kext.
And also try to figure out if there any other issues, which may not be related with nootedred compability!

**Comment by Nagendra9Kumar** [comment]
I tweak little bit now i able to boot into recovery but got problem installer stuck or crash at "about 12 minutes"
