### ISSUE TITLE
non-working touchpad

### ISSUE THREAD

**Issue by milkekXD** [saeidex/msi-modern-15#6]
uhhh

**Comment by milkitails** [comment]
i have msi modern 15 b7m

**Comment by milkitails** [comment]
oh

**Comment by milkekXD** [comment]
i have msi modern 15 b7m, 
with a ryzen 5 7530u.
the rest of the configuration seems to be identical to the modern 15 a5m.
everything works fine in monterey, even the webcam, but the touchpad doesn't.
i tried to add voodooi2c (because in windows device manager the touchpad is marked as connected via I2C bus), but I got some error.
removing/disabling voodoops2 didn't solve the problem, although i don't think that's the issue here.

**Comment by milkekXD** [comment]
![image](https://github.com/user-attachments/assets/b723127f-d98e-480d-9521-af28a26ea7b4)

i tried installing voodooI2C again, it worked, now it shows touchpad in settings but it doesn't work ! turning it on/off with the button doesn't help of course.
also lots of text like this:
VoodooI2CELAN touchpad driver: invalid report (0)
maybe it's because the touchpad is not ELAN, but in that case I don't know what to do at all. please help.
i also attach a screenshot of the installed voodooi2c and voodoops2 (for keyboard and mouse) kexts:

![Снимок экрана 2024-12-28 в 1 16 37 AM](https://github.com/user-attachments/assets/8743361a-73c5-4132-b747-de12ae7ba012)

**Comment by milkekXD** [comment]
i checked in windows again, more in depth, and found that this touchpad is ELAN after all. 
but it doesn't work with voodooi2celan. 
does anyone know what could be the problem?

**Comment by saeidex** [comment]
![Screenshot_20241228-152528.png](https://github.com/user-attachments/assets/3b747aa8-6d9d-4d74-8457-9b5612a39351)

ref: https://www.reddit.com/r/hackintosh/comments/hhf263/kext_elan_ps2_touchpad_new_kext/?rdt=49293

It supposted to work with VoodooPS2, If it doesn't work try VoodooSMBus kext.
to work with VoodooPS2, If it doesn't work try VoodooSMBus kext.

also, you can checkout this: https://www.youtube.com/watch?v=s5ehk9RletA

**Comment by saeidex** [comment]
Also, you could checkout [this commit](https://github.com/saeidex/ryzentosh-msi-modern-15/commit/2e8ee69640398829050d15cf38c5238c31d09d16)

Ensure the Trackpad plugin is inside the `VoodooPS2Controller.kext/Contents/Plugins` directory.

**Comment by milkekXD** [comment]
oh
i don't think it's gonna work in my case.
but i'm gonna try it anyway

**Comment by milkekXD** [comment]
I installed a new version of voodoops2, of course it didn't work, also the command key for some unknown reason to me, swapped with the option key.

**Comment by milkekXD** [comment]
gonna try voodoosmbus

**Comment by milkekXD** [comment]
just as i thought, voodoosmbus doesn't work either.

**Comment by milkekXD** [comment]
anyway, none of the methods worked and the touchpad still doesn't work.

**Comment by milkekXD** [comment]
and it also disappeared from the settings

**Comment by milkekXD** [comment]
the only thing I can say is that the touchpad here is definitely ELAN.
because that's what it says in windows device manager.
i reverted the configuration with voodooI2C but it still doesn't work, however the touchpad is showing up in the settings again.

![screenshot](https://github.com/user-attachments/assets/d38daf42-9c57-4bfe-b159-8d665521799a)

**Comment by saeidex** [comment]
Try [this version](https://github.com/BAndysc/VoodooPS2/releases/tag/0.4)
![image](https://github.com/user-attachments/assets/ed57d98c-4488-4887-9ed3-0cc6c744271a)

**Comment by milkekXD** [comment]
ok i'm gonna try it

**Comment by milkekXD** [comment]
again, it's not working.
i want to repeat myself, the touchpad is connected via I2C, and of course VoodooPS2 will do no good.
everything boots, but again, the system does not see the touchpad, which is confirmed by its absence in the settings.

**Comment by saeidex** [comment]
![image](https://github.com/user-attachments/assets/311cb1e5-9188-400a-a8fb-70ee1d8eb291)
re-verify the ACPI directory, make changes if needed based on your configuration.

Also order plugins correctly on `config.plist` if needed. (Also recheck PS2 or I2C using AIDA64 if possible)

**Comment by milkekXD** [comment]
to be honest, i don't know hackintosh at all, and i don't know what changes i need to make based on my configuration.
i've replaced the entire ACPI directory several times with the one I just downloaded from your repository, i haven't changed the order of kexts and plugins in the config.
and i have already attached a screenshot of the current order of plugins and kexts in another post. 
about AIDA64, i'll try to download and check it now.
i also want to note that some applications, for example Google Chrome (based on chromium) hangs and crashes, sometimes even kernel panic happens. it is written [here](https://github.com/Asqit/Ryzentosh) that applications based on electron/chromuim are laggy when dragging and dropping. 

![Снимок экрана 2024-12-28 в 7 39 02 PM](https://github.com/user-attachments/assets/edc58ced-1de5-4fe5-acdf-218c7cf59f9f)

in my case, they just freeze on startup and crash.

**Comment by milkekXD** [comment]
AIDA64 also says that my ELAN touchpad is connected via I2C

![photo_2024-12-28_17-14-48](https://github.com/user-attachments/assets/25418a64-c73d-4fc5-8a8a-b954305e83fc)

(on the screenshot it says 12C - this is probably a typo in google lens translator, the original says I2C)

**Comment by saeidex** [comment]
Sorry, I don't have any solution.

Yes, all electron / chromium based crashes and hangs in my device.

**Comment by milkekXD** [comment]
> Sorry, I don't have any solution.

 thanks anyway, at least for trying to help (≧▽≦)

**Comment by milkekXD** [comment]
LOOL. i  just had to remove VoodooI2CELAN and VoodooI2CSynaptics, leaving only VoodooI2C and VoodooI2CHID, and it works!!! with all gestures!!!!

**Comment by milkekXD** [comment]
and by the way, i think you know what a hung google chrome looks like, but i'll attach a picture anyway

![image](https://github.com/user-attachments/assets/5dc77984-0254-42d9-9427-bf4aca999a0a)
